### ISSUE TITLE
Uncaught ReferenceError: SwaggerUIBundle is not defined

### ISSUE THREAD

**Issue by Wassap124** [scttcper/koa2-swagger-ui#170]
Whenever I try to access my `/swagger` route, the aforementioned error appears in the console, and nothing will load.
I'm running all of this in `typescript`.

I'm following the instructions but nothing seems to work.

```ts
// index.ts
import Koa from "koa";
import koaSwagger from "koa2-swagger-ui";
import yaml2js from "yamljs";
import appRouter from "./routes";

const app = new Koa();
const spec = yaml2js.load("swagger.yml");
appRouter.use(koaSwagger());
appRouter.get("/swagger", koaSwagger({ routePrefix: false, swaggerOptions: { spec }}));
app.use(appRouter.routes());
```

versions:
 - koa: ^2.8.1
 - koa-router: ^7.4.0
 - koa2-swagger-ui: ^2.15.3
 - yamljs: ^0.3.0

**Comment by scttcper** [comment]
`koa2-swagger-ui: ^2.15.3` is older. the cdn link js link probably stopped working

**Comment by Wassap124** [comment]
Hey there,   
Thanks for the quick response.  
I updated to version 4.0.0 and the error persists.  
I made sure that the `spec` variable loads the configuration correctly

**Comment by scttcper** [comment]
you have it on two routes, which one are you trying? /swagger ?

**Comment by Wassap124** [comment]
Why 2?  
I'm serving it at `/swagger` and that's it.  
Are you seeing something that I'm missing?

**Comment by Wassap124** [comment]
Wait, I think I realized what the problem is.  
You try to download swagger-ui.
I see get requests fail on `cdnjs.cloudfare.com/ajax/libs/swagger-ui`.

What if I want to run everything on premise?

**Comment by masb0ymas** [comment]
<img width="1439" alt="Screen Shot 2020-10-20 at 16 51 22" src="https://user-images.githubusercontent.com/30567103/96570434-92413800-12f4-11eb-8e5d-b9874d0999ed.png">

I also can't access Swagger, because I see `GET` requests fail on `cdnjs.cloudfare.com/ajax/libs/swagger-ui`

**Comment by dkMorlok** [comment]
when you look at release files https://cdnjs.com/libraries/swagger-ui there is no script with name `swagger-ui-bundle.min.js` only `swagger-ui-bundle.js` maybe they change names of exported files.
