### ISSUE TITLE
Swagger-ui v3.38 is not loading

### ISSUE THREAD

**Issue by GustavoRSSilva** [scttcper/koa2-swagger-ui#199]
Hi, 

I am using the latest version of the koa2-swagger-ui (V5.0.5) and when loading it returns the error:

`swagger:84 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (swagger:84)`
    
The problem is that the URL "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.38.0/swagger-ui-bundle.min.js" returns a 404.

**Comment by scttcper** [comment]
this was fixed in https://github.com/scttcper/koa2-swagger-ui/commit/5d117e9e2bb79022064d73f1235c20fa5dadb35a released in v5.0.5
