### ISSUE TITLE
Its call next middle ware after url matched routePrefix, it is wrong, we don't get JSON file.

### ISSUE THREAD

**Issue by rishabhchandel** [scttcper/koa2-swagger-ui#20]
I fix it manually via edit node_modules/koa2-swagger-ui/lib/index.js
return function koaSwaggerUi(ctx, next) {
    if (options.routePrefix === false || ctx.path === options.routePrefix) {
      ctx.type = 'text/html';
      ctx.body = index(options);
      return;  **//add return here**   
    }
    return next();
  };

**Comment by scttcper** [comment]
Adding a return there ends the koa request loop. Check that you don't have something setting the body to something else. Or put the middleware behind the router you use for everything else.

**Comment by rishabhchandel** [comment]
in my case, it is middle of public and secured router. it is not possible.
