### ISSUE TITLE
Error in Building Project Using TypeScript Configuration

### ISSUE THREAD

**Issue by Qubaish** [scttcper/koa2-swagger-ui#228]
Hi, 

I am using **koa2-swagger-ui@5.8.0,** and everything is functioning properly. However, when I attempted to build the project using TypeScript configuration, I encountered the following error. Could you please assist me in resolving this issue?

Thanks

<img width="1123" alt="image" src="https://github.com/scttcper/koa2-swagger-ui/assets/8197706/c1e5ef89-c359-4b76-903f-15364364e00f">

**Comment by scttcper** [comment]
not using skipLIbCheck is insane https://www.typescriptlang.org/tsconfig#skipLibCheck
